# 컴퓨터학부 2020117066 김재홍
## Lab11
### 11-1

In [2]:
#1
import numpy as np
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
#2
a = []
for i in range(0, 10):
    a.append(i)
b = np.array(a)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
#3
a = []
for i in range(0, 10, 2):
    a.append(i)
c = np.array(a)
c

array([0, 2, 4, 6, 8])

In [10]:
#4
a = []
for i in range(0, 10, 2):
    a.append(i)
c = np.array(a)
print('c.shape =', c.shape)
print('c.ndim =', c.ndim)
print('c.dtype =', c.dtype)
print('c.size =', c.size)
print('c.itemsize =', c.itemsize)

c.shape = (5,)
c.ndim = 1
c.dtype = int64
c.size = 5
c.itemsize = 8


### 11-2

In [17]:
#1 
a = np.array([23, 45, 67, 7, 2, 30, 34, 82])
print('a = array(',a,')')
print('최댓값 : {}'.format(a.max()))
print('최솟값 : {}'.format(a.min()))
print('평균 : {}'.format(a.mean()))


a = array( [23 45 67  7  2 30 34 82] )
최댓값 : 82
최솟값 : 2
평균 : 36.25


In [21]:
#2 
b = np.random.randint(0,99, size=10)
print('b = array(',b,')')
print('최댓값 : {}'.format(b.max()))
print('최솟값 : {}'.format(b.min()))
print('평균 : {}'.format(b.mean()))

b = array( [44 85  2 32 79 60 71  2 49 37] )
최댓값 : 85
최솟값 : 2
평균 : 46.1


In [23]:
#3
c = np.append(a, b)
print('c = array(,c,')')

c = array( [23 45 67  7  2 30 34 82 44 85  2 32 79 60 71  2 49 37] )


### 11-3

In [33]:
#1
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[2, 2, 2], [2, 2, 2], [2, 2, 2]])
print('a =', a)
print('b = {}'.format(b))

print('a + b =', a + b)
print('a - b =', a - b)
print('a * b =', a * b)
print('a / b =', a / b)
print('a @ b =', a @ b)
print('a ** 2 =', a ** 2)

a = [[1 2 3]
 [4 5 6]
 [7 8 9]]
b = [[2 2 2]
 [2 2 2]
 [2 2 2]]
a + b = [[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
a - b = [[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]
a * b = [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
a / b = [[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]
a @ b = [[12 12 12]
 [30 30 30]
 [48 48 48]]
a ** 2 = [[ 1  4  9]
 [16 25 36]
 [49 64 81]]


### 11-4

In [37]:
a1 = np.full((3, 3), 2)
print('a1 =',end='')
print(a1)

a1 =[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [39]:
a2 = np.arange(1, 13)
print('a2 =',a2)

a2 = [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [40]:
a3 = np.arange(3, 50, 3)
print('a3 =', a3)

a3 = [ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48]


In [43]:
a4 = np.linspace(0.0, 20, 5)
print('a4 =', a4)

a4 = [ 0.  5. 10. 15. 20.]


### 11-5

In [45]:
#1
a1 = np.arange(1, 13)
print('a1 = ',a1.reshape(2,6))

a1 =  [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [48]:
#2
a2 = np.arange(1, 31).reshape(3, 10)
print('a2 =', a2)

a2 = [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]


In [49]:
#3
a3 = a2.reshape(6,5)
print('a3 =', a3)

a3 = [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [51]:
#4
a4 = a3.transpose()
print('a4 =', a4)

a4 = [[ 1  6 11 16 21 26]
 [ 2  7 12 17 22 27]
 [ 3  8 13 18 23 28]
 [ 4  9 14 19 24 29]
 [ 5 10 15 20 25 30]]


### 11-6

In [52]:
#1


### 11-7

In [59]:
#1
a = np.arange(1, 11)
print('a =', a)
b = a[1:9:2]
print('b =', b)

a = [ 1  2  3  4  5  6  7  8  9 10]
b = [2 4 6 8]


In [60]:
#2
