### numpy의 random사용

In [2]:
import numpy as np
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [3]:
a.shape

(3,)

In [4]:
a.ndim

1

In [5]:
a.dtype

dtype('int64')

In [6]:
a.itemsize

8

In [7]:
a.size

3

In [8]:
a = np.array([1, 2, 3, 4])
a.shape

(4,)

In [9]:
a.ndim

1

In [10]:
a.dtype

dtype('int64')

In [11]:
a.itemsize

8

In [12]:
a.size

4

In [19]:
a = np.array(1, 2, 3, 4)

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [21]:
a = np.array([1, 'two', 3, 4], dtype = np.int32)

ValueError: invalid literal for int() with base 10: 'two'

### ndarray의 메소드와 주요 함수

In [22]:
#1
a = np.array([1, 2, 3])
a.max()

3

In [23]:
a.min()

1

In [24]:
a.mean()

2.0

In [26]:
a = np.array([[1,1], [2,2], [3,3]])
a.flatten()

array([1, 1, 2, 2, 3, 3])

In [27]:
a = np.array([1, 2, 3])
b = np.array([[4, 5, 6], [7, 8, 9]])
np.append(a, b)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.append([a], b, axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
np.random.rand(3, 3)

array([[0.47798755, 0.87095813, 0.65977599],
       [0.50266801, 0.74790279, 0.00921379],
       [0.43634635, 0.49191188, 0.45451902]])

In [30]:
np.random.randint(0, 10, size = 10)

array([5, 2, 0, 0, 4, 8, 8, 0, 1, 6])

### ndarray의 연산

In [32]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a + b
c

array([5, 7, 9])

In [33]:
a = np.array([1, 2])
b = np.array([4, 5, 6])
c = a + b

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [34]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[10, 20], [30, 40]])
a + b

array([[11, 22],
       [33, 44]])

In [35]:
a - b

array([[ -9, -18],
       [-27, -36]])

In [36]:
a * b

array([[ 10,  40],
       [ 90, 160]])

In [37]:
a / b

array([[0.1, 0.1],
       [0.1, 0.1]])

In [39]:
np.matmul(a,b)

array([[ 70, 100],
       [150, 220]])

In [41]:
a @ b

array([[ 70, 100],
       [150, 220]])

In [42]:
a = np.array([[3, 4], [10, 20]])
a + 1

array([[ 4,  5],
       [11, 21]])

In [43]:
a - 1

array([[ 2,  3],
       [ 9, 19]])

In [44]:
a * 100

array([[ 300,  400],
       [1000, 2000]])

In [45]:
a / 100

array([[0.03, 0.04],
       [0.1 , 0.2 ]])

In [53]:
a ** 2

array([[  9,  16],
       [100, 400]])

### ndarry의 생성

In [48]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [49]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [51]:
np.full((2, 3), 100)

array([[100, 100, 100],
       [100, 100, 100]])

In [52]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [55]:
np.random.random((2, 3))

array([[0.90103421, 0.23111996, 0.74153547],
       [0.16780986, 0.23605494, 0.10503862]])

In [57]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [60]:
np.arange(0, 10, 3)

array([0, 3, 6, 9])

In [61]:
np.arange(0.0, 1.0, 0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [62]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [63]:
np.linspace(0, 10, 4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

### ndarray의 재구성

In [64]:
np.arange(0, 10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [65]:
np.arange(0, 10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [67]:
np.arange(0, 10).reshape(3, 3)

ValueError: cannot reshape array of size 10 into shape (3,3)

In [68]:
np.arange(0, 24).reshape(4, 3, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [70]:
a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [71]:
np.transpose(a)

array([[0, 2, 4],
       [1, 3, 5]])

In [77]:
a = np.array([[1, 2, 3], [4, 5, 6]])
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [78]:
print(a)

[[1 2 3]
 [4 5 6]]


In [81]:
print(np.array2string(a, separator=", "))

[[1, 2, 3],
 [4, 5, 6]]


In [82]:
print(repr(a))

array([[1, 2, 3],
       [4, 5, 6]])


### 다차원 배열의 축

In [83]:
a = np.arange(0, 6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [84]:
a.sum()

15

In [85]:
a.sum(axis = 0)

array([6, 9])

In [86]:
a.sum(axis = 1)

array([1, 5, 9])

In [87]:
a.min(axis = 0)

array([0, 1])

In [88]:
a.min(axis = 1)

array([0, 2, 4])

In [89]:
a.max(axis = 0)

array([4, 5])

In [90]:
a.max(axis = 1)

array([1, 3, 5])

### ndarray의 insert() 함수

In [92]:
a = np.array([1, 3, 4])
np.insert(a, 1, 2)

array([1, 2, 3, 4])

In [93]:
a = np.array([[1, 1], [2, 2], [3, 3]])
np.insert(a, 1, 4, axis = 0)

array([[1, 1],
       [4, 4],
       [2, 2],
       [3, 3]])

In [94]:
np.insert(a, 1, 4, axis = 1)

array([[1, 4, 1],
       [2, 4, 2],
       [3, 4, 3]])

### 배열의 인덱싱과 슬라이싱

In [95]:
a = np.array([1, 2, 3])
print(a[0], a[1], a[2])
print(a[-1], a[-2], a[-3])


1 2 3
3 2 1


In [97]:
a = np.array([1, 2, 3, 4, 5])
print(a[np.array([0, 1])])

[1 2]
